name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.5',
          - '2.6',
          - '2.7',
          - '3.0',
          - '3.1',
          - '3.2',
          - '3.3',
          - '3.4',
          - 'head'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        cache-version: 2
    - name: Run tests
      run: bundle exec rake --trace
      env:
        RUBYOPT: "--disable-frozen-string-literal" # Silence these warnings for now.
